version: "3.8"
services:
    nodeserver:
        restart: unless-stopped
        build:
            context: ./app
        depends_on: 
          - mongo
        links:
          - "mongo"
        networks:
          - app-network
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "0.0.0.0:80:80"
        links:
          - "nodeserver"
        depends_on:
          - nodeserver
        networks:
          - app-network
    mongo:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        networks:
          - app-network
    mongoimport:
        image: mongo
        depends_on:
          - mongo
        restart: "no"
        volumes:
          - ./mongodb/prevloginlogs.json:/mongodb/prevloginlogs.json
          - ./mongodb/users.json:/mongodb/users.json
          - ./mongodb/import.sh:/mongodb/import.sh
        networks:
          - app-network
        entrypoint: [ "bash", "-c", "sleep 10 && sh /mongodb/import.sh"]
    
networks:
  app-network:
    driver: bridge 